// Liste partagée des pays africains (code ISO2, indicatif, drapeau, nom FR).
// Utilisée par la page de publication d'annonce (sell.js) et la page de
// recherche d'annonces (properties/index.js) pour rester cohérentes.
export const AFRICAN_COUNTRIES = [
  { code: "ZA", dial: "+27",  flag: "🇿🇦", name: "Afrique du Sud" },
  { code: "DZ", dial: "+213", flag: "🇩🇿", name: "Algérie" },
  { code: "AO", dial: "+244", flag: "🇦🇴", name: "Angola" },
  { code: "BJ", dial: "+229", flag: "🇧🇯", name: "Bénin" },
  { code: "BW", dial: "+267", flag: "🇧🇼", name: "Botswana" },
  { code: "BF", dial: "+226", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "BI", dial: "+257", flag: "🇧🇮", name: "Burundi" },
  { code: "CM", dial: "+237", flag: "🇨🇲", name: "Cameroun" },
  { code: "CV", dial: "+238", flag: "🇨🇻", name: "Cap-Vert" },
  { code: "KM", dial: "+269", flag: "🇰🇲", name: "Comores" },
  { code: "CG", dial: "+242", flag: "🇨🇬", name: "Congo" },
  { code: "CI", dial: "+225", flag: "🇨🇮", name: "Côte d'Ivoire" },
  { code: "DJ", dial: "+253", flag: "🇩🇯", name: "Djibouti" },
  { code: "EG", dial: "+20",  flag: "🇪🇬", name: "Égypte" },
  { code: "ER", dial: "+291", flag: "🇪🇷", name: "Érythrée" },
  { code: "SZ", dial: "+268", flag: "🇸🇿", name: "Eswatini" },
  { code: "ET", dial: "+251", flag: "🇪🇹", name: "Éthiopie" },
  { code: "GA", dial: "+241", flag: "🇬🇦", name: "Gabon" },
  { code: "GM", dial: "+220", flag: "🇬🇲", name: "Gambie" },
  { code: "GH", dial: "+233", flag: "🇬🇭", name: "Ghana" },
  { code: "GN", dial: "+224", flag: "🇬🇳", name: "Guinée" },
  { code: "GQ", dial: "+240", flag: "🇬🇶", name: "Guinée équatoriale" },
  { code: "GW", dial: "+245", flag: "🇬🇼", name: "Guinée-Bissau" },
  { code: "KE", dial: "+254", flag: "🇰🇪", name: "Kenya" },
  { code: "LS", dial: "+266", flag: "🇱🇸", name: "Lesotho" },
  { code: "LR", dial: "+231", flag: "🇱🇷", name: "Libéria" },
  { code: "LY", dial: "+218", flag: "🇱🇾", name: "Libye" },
  { code: "MG", dial: "+261", flag: "🇲🇬", name: "Madagascar" },
  { code: "MW", dial: "+265", flag: "🇲🇼", name: "Malawi" },
  { code: "ML", dial: "+223", flag: "🇲🇱", name: "Mali" },
  { code: "MA", dial: "+212", flag: "🇲🇦", name: "Maroc" },
  { code: "MU", dial: "+230", flag: "🇲🇺", name: "Maurice" },
  { code: "MR", dial: "+222", flag: "🇲🇷", name: "Mauritanie" },
  { code: "MZ", dial: "+258", flag: "🇲🇿", name: "Mozambique" },
  { code: "NA", dial: "+264", flag: "🇳🇦", name: "Namibie" },
  { code: "NE", dial: "+227", flag: "🇳🇪", name: "Niger" },
  { code: "NG", dial: "+234", flag: "🇳🇬", name: "Nigeria" },
  { code: "UG", dial: "+256", flag: "🇺🇬", name: "Ouganda" },
  { code: "CD", dial: "+243", flag: "🇨🇩", name: "RD Congo" },
  { code: "CF", dial: "+236", flag: "🇨🇫", name: "République centrafricaine" },
  { code: "EH", dial: "+212", flag: "🇪🇭", name: "République arabe sahraouie démocratique" },
  { code: "RW", dial: "+250", flag: "🇷🇼", name: "Rwanda" },
  { code: "ST", dial: "+239", flag: "🇸🇹", name: "Sao Tomé-et-Principe" },
  { code: "SN", dial: "+221", flag: "🇸🇳", name: "Sénégal" },
  { code: "SC", dial: "+248", flag: "🇸🇨", name: "Seychelles" },
  { code: "SL", dial: "+232", flag: "🇸🇱", name: "Sierra Leone" },
  { code: "SO", dial: "+252", flag: "🇸🇴", name: "Somalie" },
  { code: "SD", dial: "+249", flag: "🇸🇩", name: "Soudan" },
  { code: "SS", dial: "+211", flag: "🇸🇸", name: "Soudan du Sud" },
  { code: "TZ", dial: "+255", flag: "🇹🇿", name: "Tanzanie" },
  { code: "TD", dial: "+235", flag: "🇹🇩", name: "Tchad" },
  { code: "TG", dial: "+228", flag: "🇹🇬", name: "Togo" },
  { code: "TN", dial: "+216", flag: "🇹🇳", name: "Tunisie" },
  { code: "ZM", dial: "+260", flag: "🇿🇲", name: "Zambie" },
  { code: "ZW", dial: "+263", flag: "🇿🇼", name: "Zimbabwe" },
];
